version: '3'

services:
  db:
    container_name: nextcloud_db
    build: ./db
    restart: always
    volumes:
      - ${NEXTCLOUD_DATA_PATH}nextcloud_db:/var/lib/mysql
      - ./db/myconfig.cnf:/etc/mysql/conf.d/myconfig.cnf:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}

  app:
    container_name: nextcloud
    build: ./nextcloud
    ports:
      - ${NEXTCLOUD_HTTP_PORT}:80
    links:
      - db
    volumes:
      # - ${NEXTCLOUD_DATA_PATH}nextcloud:/var/www/html
      - ${NEXTCLOUD_DATA_PATH}nextcloud_data:/var/www/html/data
      - ${NEXTCLOUD_DATA_PATH}nextcloud_config:/var/www/html/config
      - ${NEXTCLOUD_DATA_PATH}nextcloud_apps:/var/www/html/custom_apps
      - ./nextcloud/my.config.php:/var/www/html/config/my.config.php:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
     - NEXTCLOUD_ADMIN_USER=admin
     - NEXTCLOUD_ADMIN_PASSWORD=admin
     - MYSQL_DATABASE=${MYSQL_DATABASE}
     - MYSQL_USER=${MYSQL_USER}
     - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    # - MY_SQL_HOST=db
     - MYSQL_HOST=db
    restart: always
