version: '3'

volumes:
  nextcloud:
  nextcloud_data:
    external: true
  nextcloud_config:
    external: true
  nextcloud_db:
    external: true
  nextcloud_apps:
    external: true
  

services:
  db:
    container_name: nextcloud_db
    #image: jsurf/rpi-mariadb
    build: ./db
    restart: always
    volumes:
      - nextcloud_db:/var/lib/mysql
      - ./db/myconfig.cnf:/etc/mysql/conf.d/myconfig.cnf:ro
    #  - /etc/timezone:/etc/timezone:ro
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
    networks:
      - discovery

  app:
    container_name: nextcloud
    build: ./nextcloud
    ports:
      - ${NEXTCLOUD_HTTP_PORT}:80
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
      - nextcloud_data:/var/www/html/data
      - nextcloud_config:/var/www/html/config
      - nextcloud_apps:/var/www/html/custom_apps
      - ./nextcloud/my.config.php:/var/www/html/config/my.config.php
    #  - /etc/timezone:/etc/timezone:ro
    labels:
     - "traefik.enable=true"
     - "traefik.frontend.rule=PathPrefixStrip:${NEXTCLOUD_PATHPREFIX}"
     - "traefik.frontend.priority=1"
     - "traefik.docker.network=discovery"
     - "traefik.backend=nextcloud"
     - "traefik.port=80" #point to port that container locally wants
    environment:
     - NEXTCLOUD_ADMIN_USER=admin
     - NEXTCLOUD_ADMIN_PASSWORD=admin
     - MYSQL_DATABASE=${MYSQL_DATABASE}
     - MYSQL_USER=${MYSQL_USER}
     - MYSQL_PASSWORD=${MYSQL_PASSWORD}
     - MY_SQL_HOST=db
    restart: always
    networks:
      - discovery

networks:
  discovery:
    external: true