version: '2'

volumes:
  nextcloud:
  db:

services:
  db:
    image: jsurf/rpi-mariadb
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
    networks:
      - discovery

  app:
    image: nextcloud
    ports:
      - ${NEXTCLOUD_HTTP_PORT}:80
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
    labels:
     - "traefik.enable=true"
     - "traefik.frontend.rule=PathPrefixStrip:${NEXTCLOUD_PATHPREFIX}"
     - "traefik.frontend.priority=1"
     - "traefik.docker.network=discovery"
     - "traefik.backend=nextcloud"
     - "traefik.port=80" #point to port that container locally wants
    environment:
     - NEXTCLOUD_ADMIN_USER=admin
     - NEXTCLOUD_ADMIN_PASSWORD=admin
     - MYSQL_DATABASE=${MYSQL_DATABASE}
     - MYSQL_USER=${MYSQL_USER}
     - MYSQL_PASSWORD=${MYSQL_PASSWORD}
     - MY_SQL_HOST=db
    restart: always
    networks:
      - discovery

networks:
  discovery:
    external: true